### ISSUE TITLE
NTR: methyl-c sequencing assay

### ISSUE THREAD

**Issue by patrick-lloyd-ray** [patrick-lloyd-ray/TMN#5]
## Preferred term label

methyl-c sequencing assay

## Synonyms

mC-seq2

## Textual definition

A sequencing assay (library preparation method) that involves fragmentation of genomic DNA followed by adapter ligation, bisulfite conversion and limited amplification using adapter-specific PCR primers in preparation for sequencing. This enables the genome-wide indentification of cytosine DNA methylation states at single-base resolution. 

## Suggested parent term

sequencing assay (OBI:0600047)

## Attribution

0000-0002-5260-9315

**Comment by patrick-lloyd-ray** [comment]
This term already exists: OBI:000204 'MethylC-Capture sequencing assay'. 

Def: "A bisulfite sequencing assay in which a whole-genome sequencing library is prepared, bisulfite converted and amplified, followed by a capture enriching for targeted bisulfite-converted DNA fragments that are are subsequently identified by DNA sequencing."

Is this an alternative term or a distinct class? @jimmymathews do you happen to know?

**Comment by jimmymathews** [comment]
Most likely there's nothing new to add here, not a new term.

The datasets we have tagged for mC-seq2 come from the Ecker lab:
https://biccn.org/teams/u01-ecker
https://biccn.org/teams/u19-ecker

Note: On those pages there is reference to "snmC-seq". I believe the Ecker lab originally supplied this term in the description of their data collections, but Carol removed the "sn" since it means "single nucleus", i.e. information about the kind of specimens that were assayed and not really the assay itself.

As for the "2" suffix, I wasn't able to find any documented differentia. Note that the pages linked above also reference "snmC-seq3".

**Comment by jimmymathews** [comment]
The protocol the Ecker lab documented
https://www.protocols.io/view/methyl-c-sequencing-of-single-cell-nuclei-snmc-seq-pjvdkn6

seems to refer to "snmC-seq" and "snmC-seq2" interchangeably (e.g. in section/document titles).

**Comment by patrick-lloyd-ray** [comment]
Thanks! The second document is especially helpful. 

'mcc-seq' is an alternative term for the aforementioned class. I could add 'snmC-seq' but given that 'sn' seems superfluous, I doubt there is anything to change. Closing for now.
